### ISSUE TITLE
WSL2 Build Breaks

### ISSUE THREAD

**Issue by colinoflynn** [CHERIoT-Platform/llvm-project#23]
The tools will not build on WSL2, this was an issue reported here: https://github.com/clangd/clangd/issues/835

The fix is in this commit: https://github.com/llvm/llvm-project/commit/4ad9ec8a328ccb3b836c993bba954366f05b2fd4

I tested this by applying that patch and building with WSL2:

```
wget https://github.com/llvm/llvm-project/commit/4ad9ec8a328ccb3b836c993bba954366f05b2fd4.patch
git am < 4ad9ec8a328ccb3b836c993bba954366f05b2fd4.patch
```

If you'd like I can open a PR with this commit cherry picked, but I wasn't sure if (a) it was an acceptable fix, and (b) if that was the best method of getting the fix (or will this later be merged into something else, so you don't want a random cherry-picked commit in there).

**Comment by marnovandermaas** [comment]
I think this is quite reasonable, I've made PR for convenience.
