### ISSUE TITLE
big data changes not working?

### ISSUE THREAD

**Issue by sleffler** [CHERIoT-Platform/llvm-project#26]
I finally tried the changes to support large'ish data structures but can't seem to get any examples to WAI (they fault and the code generated for addressing seems wrong). For example, an unfinished cheriot-rtos test case like this:
```
#include "cheri.hh"
#define TEST_NAME "Big Data"
#include "tests.hh"

extern "C" enum ErrorRecoveryBehaviour
compartment_error_handler(struct ErrorState *frame, size_t mcause, size_t mtval)
{
        debug_log("Detected error in instruction {}", frame->pcc);
        debug_log("Error cause: {}, mtval: {}", mcause, mtval);
        return ErrorRecoveryBehaviour::ForceUnwind;
}

void test_big_data()
{
  static uint32_t data[16000];
  debug_log("Fill with for loop");
  for (int i = 0; i < 16000; ++i) { data[i] = 0x01020304; }
  debug_log( "Fill with memset");
  memset(data, 0x5a, sizeof(data));
}
```
faults on the for loop and inside the memset.

Are the above uses expected to work? Are there examples of intended use?

**Comment by davidchisnall** [comment]
Thanks.  If I add this line to your test:

```
debug_log("Data: {}", data);
```

I see:

```
Big Data test: Data: 0x20054000 (v:0 0x20054000-0x20063a00 l:0xfa00 o:0x0 p: G RWcgm- -- ---)
```

So the length is correct in the generated capability, but the tag is not set.  If I also log cgp, I get this:

```
Big Data test: CGP: 0x2005c000 (v:1 0x2005c000-0x2005c000 l:0x0 o:0x0 p: G RWcgm- -- ---)
```

So it looks as if the compiler is correct, but there's something in either the linker script or the loader that's causing this to not be within the bounds of cgp and so not fail.  I'll investigate.

**Comment by davidchisnall** [comment]
Closing this here, as the compiler appears to be working correctly.  Opened the above RTOS bug to track it.
