### ISSUE TITLE
Query over need / use of __mutli3() 

### ISSUE THREAD

**Issue by PhilDay-CT** [CHERIoT-Platform/llvm-project#52]
When porting [libhydrogen](https://github.com/jedisct1/libhydrogen) to cheriot the linker complained that __multi3() was not defined.

It seems that the call was generated by the [hydro_x25519_umaal()](https://github.com/jedisct1/libhydrogen/blob/576a38bfd14357326a9727f977b46014363eeec8/impl/x25519.h#L52) function.

__multi3() is defined in [gcc](https://gcc.gnu.org/onlinedocs/gccint/Integer-library-routines.html) as 
```
Runtime Function: long long __multi3 (long long a, long long b)
```

Following discussion with @davidchisnall I implement this as a 64-bit multiply:
https://github.com/CHERIoT-Platform/cheriot-rtos/commit/2b98b899c3bbdab8620303db1f240e9a14f920f0 

However although this allowed libHydrogen to compile it didn't run as expected on cheriot.  Specifically:
- Signatures generated on cheriot failed to validate on linux based version of libhydrogen
- All calls to signature validation on cheriot returned success regardless of the signature passed in. 

Compiling libhydrogen in 32-bit mode on Cheriot (by adjusting the defines at  the top of [impl/x25519.h](https://github.com/jedisct1/libhydrogen/blob/576a38bfd14357326a9727f977b46014363eeec8/impl/x25519.h#L7) did give a version which properly generates and validates signatures - and does not require __multi3().

All of which makes me wonder if the compiler when it chose to inject the call to  __multi3() is expecting a function to operate on int128_t types - a direct multiply of  two int64_t values doesn't generate a call to __multi3()

__multi3() is the only one of the "long long" functions now implemented in [arith64.h](https://github.com/CHERIoT-Platform/cheriot-rtos/blob/main/sdk/lib/crt/arith64.c) - I no longer need it for the libHydrogen port - but worry I may have created a trap for the future if this isn't the implementation the compiler expects.

**Comment by resistor** [comment]
Working on reproducing this...

**Comment by resistor** [comment]
I can reproduce it. The issue does not reproduce with LLVM 17. I'll see if I can find the root cause.

**Comment by resistor** [comment]
The root cause is that LLVM 13 is defining `__SIZEOF_INT128__` while LLVM 17 is not. This caused the compiler to emit 128-bit arithmetic in the former case, eventually resulting in the library call being emitted.

**Comment by resistor** [comment]
Alex fixed it upstream in https://github.com/llvm/llvm-project/commit/a602f76a2406cc3edd6b297ede3583b26513a34c

**Comment by resistor** [comment]
@PhilDay-CT I believe your implementation of `__multi3` can stand, though it shouldn't end up being called. LLVM was incorrectly assuming `__multi3` would operation on `__int128`'s, when in fact it operates on `long long`'s, which are 64-bits on Cheriot.

**Comment by PhilDay-CT** [comment]
@resistor - thanks for looking into this, and the explanation.    So if I understand correctly this will be fixed once this repo updates to LLVM 17 ?   Is there some where I can track that so I know when to remove my current workaround ?

**Comment by resistor** [comment]
@PhilDay-CT That's correct. It should happen any day now, we're just waiting for our upstream to cut their branch over as well.
