### ISSUE TITLE
Use `tp` as extra temporary register?

### ISSUE THREAD

**Issue by rmn30** [CHERIoT-Platform/llvm-project#53]
The RISC-V ABI specifies `x4` as the "thread pointer", `tp`. I think it's currently unused except in assembly code. We should think about using it as an extra temporary register.

**Comment by resistor** [comment]
Staged in https://github.com/resistor/llvm-project-1/commit/7437be589fe39299275896396ea2e84395c063e9

**Comment by rmn30** [comment]
We should probably have this behind a compiler flag just in case it needs to be used for its intended purpose.

**Comment by davidchisnall** [comment]
We already have a way of requesting the thread ID.  I don't think there's any value in making this conditional.  The concept of TLS doesn't make sense in CHERIoT and we already have an ABI for compartment-invocation-local storage.

**Comment by rmn30** [comment]
Nice. @resistor did you measure any space / performance differences with / without this?

**Comment by resistor** [comment]
When I tried I didn't detect any change. I suspect we're not limited by register pressure under normal conditions.

**Comment by davidchisnall** [comment]
Good data for the people who keep saying 'Oh no, CHERIoT only has 16 registers, we need 32 because of reasons!'
