### ISSUE TITLE
Teach the optimizer that `candperms` is idempotent

### ISSUE THREAD

**Issue by nwf** [CHERIoT-Platform/llvm-project#59]
The compiler is smart enough to common-up the load-immediates in something like (hypothetical syntax)
```
li %0, N
candperms %2, %1, %0
li %3, N
candperms %4, %2, %3
```
resulting in
```
li %0, N
candperms %2, %1, %0
candperms %4, %2, %0
```
and, if `%1` is dead thereafter, it can even make this
```
li %0, N
candperms %1, %1, %0
candperms %1, %1, %0
```
but it doesn't know that `candperms` is idempotent, so the two stick around.

This is coming up because I am toying with making some code that has to work in both C and C++ ([`struct Timeout`](https://github.com/CHERIoT-Platform/cheriot-rtos/blob/7cf893ef1b83ddcb2f8880eab141bd13456c43d4/sdk/include/timeout.h#L31), specifically) prefer `candperms`-mediated views of `this`.  In C++, overloading `operator&` gets us the behavior we want without making changes to C++ code that takes addresses of `struct Timeout` objects, but because some code has to be both C++ and C (where there's a distinct lack of user-controlled operator overloading), that code has to manually insert `__builtin_cheri_perms_and(&timeout, ...)` to get the correct behavior in C, but then gets the two `candperms` in C++. Sigh.

**Comment by resistor** [comment]
I believe this would be fixed by this: https://github.com/resistor/llvm-project-1/commit/1bf8701d200e781a400916e332c324db673f2b8e

**Comment by nwf** [comment]
Ah, fantastic.  Two bugs with one patch.  (Will test tomorrow, but if so, then it's also correct that CAndPerm cannot trap.)

**Comment by nwf** [comment]
Alas,
```c++
Capability<void> oLocal2 = o;
oLocal2.without_permissions(Permission::Global);
oLocal2.without_permissions(Permission::Global);
```
still compiles to
```
80015252: 05 66        	lui	a2, 1
80015254: 79 16        	addi	a2, a2, -2
...
8001525e: 5b 05 c5 1a  	candperm	ca0, ca0, a2
80015262: 5b 05 c5 1a  	candperm	ca0, ca0, a2
```

**Comment by resistor** [comment]
Ah, I misunderstood the nature of the redundancy here. The mayTrap fix is good in general, but wouldn't resolve this redundancy. We'll need a new InstCombine
