### ISSUE TITLE
LLVM 17 upgrade CI breakage: Cirrus CI timeout after 2h, some failing tests

### ISSUE THREAD

**Issue by v01dXYZ** [CHERIoT-Platform/llvm-project#64]
It's maybe correlated to the upgrade to LLVM 17 that requires more room. Or it could be a new policy from Cirrus itself.

**Comment by resistor** [comment]
I increased the timeout to 4 hours, and changed the CI config to reduce build times. If you rebase onto the newest commits on the `cheriot` branch it should be better.

**Comment by resistor** [comment]
Semi-relatedly, there's some tests broken in CI that came in from CHERI upstream. Proposed fixes are here: https://github.com/CHERIoT-Platform/llvm-project/pull/65

**Comment by resistor** [comment]
Alright, CI seems to be in a good state for now. Let me know if you run into any more issues.
